name: canvas_365
description: A new Flutter project.
homepage: https://github.com/fluttercandies/flutter_image_editor
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #reviews_slider: "^1.0.4"
  http: ^0.13.0
  #toast: ^0.1.5
  fluttertoast: ^8.0.8
    #shared_preferences: ^0.5.12+4
  shared_preferences: ^2.0.6
  rolling_bottom_bar: ^0.2.2
  delayed_display: ^2.0.0
  bouncing_widget: ^2.0.0
  carousel_slider: ^4.0.0
  http_auth: ^1.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.14
  country_list_pick: ^1.0.1+5
  pin_code_fields: ^7.3.0
  chips_choice: ^3.0.0
  #marquee: ^2.2.0
  #flutter_point_tab_bar: ^0.2.0
  dotted_border: ^2.0.0+1
  image_picker: ^0.8.5
  flutter_share: ^2.0.0
#  path_download: ^0.0.3
  lecle_downloads_path_provider: ^0.0.2+8
  animated_splash_screen: ^1.1.0
#  video_thumbnail: ^0.4.3
#  image_gallery_saver: ^1.7.1
  razorpay_flutter: ^1.2.7
  gallery_saver: ^2.3.1
#  video_player: ^2.2.5
  better_video_player: ^1.2.8
  flutter_circle_color_picker: ^0.3.0
  google_fonts: ^4.0.1
  roundcheckbox: ^2.0.5
  lottie: ^2.0.0
  getwidget: ^3.0.1
  path_provider: ^2.0.9
  dio: ^4.0.0
  open_file_safe: ^3.2.3
  file_picker: ^4.1.3
  share: ^2.0.4
  intl: ^0.18.0
  font_awesome_flutter: ^10.2.1
  cached_network_image: ^3.1.0+1
  image_editor: ^1.0.2
  email_validator: ^2.0.1
  image_cropper: ^3.0.1
  photofilters: ^3.0.1
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.0.0
  #extended_image: ^5.1.3
  photo_view: ^0.14.0
  #camera: ^0.8.1+3
  #camera: ^0.9.4+10
  camera: ^0.10.0+4
  flutter_colorpicker: ^1.0.2
  expandable: ^5.0.1
  giphy_get: ^3.1.1
  photo_gallery: ^1.1.1
  flutter_screenutil: ^5.0.0-nullsafety.2
  sn_progress_dialog: ^1.0.3
  ffmpeg_kit_flutter_min_gpl: ^5.1.0
  flutter_video_info: ^1.2.0
  device_info_plus: ^4.0.0

  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.9
  firebase_messaging: ^14.1.1
  purchases_flutter: ^5.2.3
  flutter_local_notifications: ^12.0.3
  syncfusion_flutter_pdf: ^20.3.57
  url_launcher: ^6.0.20
#  firebase_core: ^1.12.0
#  firebase_messaging: ^11.2.8
#  flutter_local_notifications: ^9.3.3
  #video_manipulation: ^0.1.7
  #gallery_saver: ^2.2.0
  #search_widget: ^1.0.2

dependency_overrides:
  package_info_plus: any
  package_info_plus_windows: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  #Bacnkground Colour
  color: "#FFFFFF"
  image: assets/images/logo.png

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#    - assets/images/ins_logo.png
    - assets/lottieFiles/
    - assets/images/

  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/Varela.ttf
    - family: Poppinsregular
      fonts:
        - asset: assets/fonts/Poppinsregular.ttf
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt.ttf
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages